### PR TITLE
Major maintainance

### PR DESCRIPTION
**Pull request by hasecilu**
I like parametric WB and like the idea of STEMFIE so I decided to prettify this WB.

Consider accepting this PR and I can add it to the FreeCAD Addon Manager.

On `package.xml` file, see https://spdx.org/licenses/ -- note that you might actually mean LGPL-2.0-only, in which case use that instead.

- [X] Upgrade workbench structure
- [X] Update WB icon
- [X] Add ViewProvider, uses WB when pixmap is not svg file
- [X] Add translation support
- [X] Add Spanish translation
- [X] Objects get a random color when created
- [X] Apply formatting to code (the same is used on main FreeCAD)
- [X] Fix some tooltips
- [X] Add plates
- [X] Add shaft
- [X] Add icons for connectors
- [ ] Regarding translation would you like to add it to CrowdIn platform where other translators work on main FreeCAD and FreeCAD addons?

2024-10-21-162522_hyprshot

Related #1

### CODE REVIEW

**Comment by Stemfie3D** [comment]
Thank you for improving the STEMFIE FreeCAD Workbench. :)

**Comment by hasecilu** [comment]
Hi @Stemfie3D, I'm trying to add more components to the workbench but I really don't find specification of the system, maybe some drawing. I found the main dimensions in the FreeCAD template but still it feels like there is missing data like in the hexagonal plate where it states being 3BU on size but measuring on FreeCAD it only measures $34.15mm$ instead of $37.5mm$ and calculating corner to corner would be $39.43mm$ to at the end having the 3BU distance from rounded corners, having to reverse engineer all dimensions only will make it harder to progress.

Meanwhile I'm making more progress in https://github.com/hasecilu/StemfieWB/tree/feat/plates

**Comment by hasecilu** [comment]
For the moment I did the changes I wanted to, maybe I can continue in 2 weeks, if someone wants to send more changes let me know.

@Ander-BM @disenator @dmarofer @kurtsik @saulmayo Are you planning to support this WB? I see is abandoned for 3 years, I can take on the maintainership on this repo if you invite me, else I would continue on my fork and add it to the FreeCAD Addons list.

image

**Comment by dmarofer** [comment]
Hi @hasecilu , thank you for your contribution!!

In fact, the project has been frozen for 3 years, but there is no problem in inviting you to manage it. I have added you as a maintainer, if you have any problems we will solve them.

**Comment by hasecilu** [comment]
Hi thanks for the invitation, I already sent a PR to add it to Addon Manager.

I want to add a tag to latest commit in order the WB has a version number, I think `0.1.0` would be ok to start, probably `1.0.0` when all components are available and maybe incrementing minor version every time a group of components is added. I'll put WIP on `develop` branch.

**Pull request merged**
